UserContext:
  allOf:
  - "$ref": https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This data model describe the Context of a User. No personal data is encoded in the model. The actual
    User data are stored in a different end point, as identified by the refUser property..
  properties:
    address:
      "$ref": https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: https://schema.org/Text
      type: string
      description: ''
    areaServed:
      x-ngsi:
        type: Property
        model: https://schema.org/Text
      type: string
      description: ''
    dataProvider:
      x-ngsi:
        type: Property
        model: https://schema.org/Text
      type: string
      description: 'Specifies the URL to information about the provider of this information'
    description:
      "$ref": https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    location:
      "$ref": https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    name:
      "$ref": https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        anyOf:
        - type: string
          minLength: 1
          maxLength: 256
          pattern: "^[\\w\\-\\.\\{\\}\\$\\+\\*\\[\\]`|~^@!,:\\\\]+$"
        - type: string
          format: uri
    refActivity:
      x-ngsi:
        type: Relationship
      description: 'An object representing the current activity performed by the User'
      type: string
      format: uri
    refUserDevice:
      x-ngsi:
        type: Relationship
      description: 'An object representing the current device used by the User.'
      type: string
      format: uri
    refUser:
      x-ngsi:
        type: Relationship
      description: 'reference to the (anonymised) User to which this UserContext is associated.'
      type: string
      format: uri
    source:
      x-ngsi:
        type: Property
        model: https://schema.org/Text
      type: string
      description: 'A sequence of characters giving the source of the entity data.'
