UserContext:
  required:
    - id
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This data model describe the Context of a User. No personal data is encoded in the model. The actual
    User data are stored in a different end point, as identified by the refUser property..
