Activity:
  required:
    - activityType
    - refAgent
    - type
    - id
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This entity represents the current activity performed by a User. It can be used in different scenarios,
    from modeling social activities on a site (e.g. Federico shares a picture of his dog) to real life activities 
    (e.g. Federico drives his car to work). The model is largely inspired by https://www.w3.org/TR/activitystreams-core.

    The model represents user activities using the following predicate structure: (Agent, Verb, Object*, Target*), where Object and Target are optional.
    The Agent is identified by the attribute refAgent, the Verb is identified by activityType, the Object is identified by refObject, and the Target is identified by refTarget.
  properties:
    activityType:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: 'The action performed (e.g. Drive).'
    alternateName:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/alternateName
    dataProvider:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/dataProvider
    dateActivityEnded:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: "Activity's end timestamp."
      format: date-time
    dateActivityStarted:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: "Activity's start timestamp."
      format: date-time
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      $ref: https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/owner
    refAgent:
      x-ngsi:
        type: Relationship
        model: 'https://schema.org/URL'
      description: 'Reference to the agent (i.e. a person) performing the activity. It may be another NGSI Entity or any Agent identified by an URI.'
      type: string
      format: uri
    refObject:
      x-ngsi:
        type: Relationship
        model: 'https://schema.org/URL'
      description: 'Reference to the object of the action (e.g. Car1). It may be another NGSI Entity or any Object identified by an URI.'
      type: string
      format: uri
    refTarget:
      x-ngsi:
        type: Relationship
        model: 'https://schema.org/URL'
      description: 'Reference to the target of the action (e.g. Office1).'
      type: string
      format: uri
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: 'A sequence of characters giving the source of the entity data.'