Activity:
  required:
    - id
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This entity represents the current activity performed by a User. It can be used in different scenarios,
    from modeling social activities on a site (e.g. Federico shares a picture of his dog) to real life activities 
    (e.g. Federico drives his car to work). The model is largely inspired by https://www.w3.org/TR/activitystreams-core.

    The model represents user activities using the following predicate structure: (Agent, Verb, Object*, Target*), where Object and Target are optional.
    The Agent is identified by the attribute refAgent, the Verb is identified by activityType, the Object is identified by refObject, and the Target is identified by refTarget.
